# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/.next' # Asegúrate de apuntar a la carpeta correcta
    includeRootFolder: false  # Cambiado a false para no incluir la carpeta raíz en el archivo comprimido
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive Next.js build files'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'oberontsi'
    appType: 'webAppLinux'
    appName: 'oberontsi'
    package: '$(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip'