export enum FileTypes {
  USER_SIGN_FILE = 'USER_SIGN_FILE',
  CANDIDATE_MILITARY_BOOK_FILE = 'CANDIDATE_MILITARY_BOOK_FILE',
  CANDIDATE_DOCUMENT_FILE = 'CANDIDATE_DOCUMENT_FILE',
  CANDIDATE_CV_FILE = 'CANDIDATE_CV_FILE',
  CANDIDATE_REFERENCE_PERSONAL = 'CANDIDATE_REFERENCE_PERSONAL',
  CANDIDATE_ACADEMIC_DIPLOMA = 'CANDIDATE_ACADEMIC_DIPLOMA',
  CANDIDATE_ACADEMIC_CERTIFICATE = 'CANDIDATE_ACADEMIC_CERTIFICATE',
  CANDIDATE_EMPLOYMENT_CERTIFICATE = 'CANDIDATE_EMPLOYMENT_CERTIFICATE',
}
