export enum EModules {
  STUDIES = 1,
  HISTORY_OF_SERVICES = 2,
  BASIC_CONSULTATION = 3,
  QA = 4,
  PARAMETRIC_LISTS = 5,
  OPERATIONAL_GROUPS = 6,
  USERS = 7,
  ROLES = 8,
  CUSTOMER_PARAMETERS = 9,
  REPORTS = 10,
  REQUESTS = 11,
}
